
    import React, { createContext, useState, useContext, useEffect } from 'react';

    const LanguageContext = createContext();

    export const translations = {
      ar: {
        appName: "فاست فيكس",
        tagline: "صيانة الأجهزة المنزلية بسرعة وكفاءة",
        customer: "عميل",
        technician: "فني",
        selectUserType: "اختر نوع المستخدم",
        login: "تسجيل الدخول",
        email: "البريد الإلكتروني",
        password: "كلمة المرور",
        forgotPassword: "هل نسيت كلمة المرور؟",
        createNewAccount: "إنشاء حساب جديد",
        register: "تسجيل",
        fullName: "الاسم الكامل",
        confirmPassword: "تأكيد كلمة المرور",
        fullAddress: "العنوان الكامل",
        mobileNumber: "رقم الجوال",
        specializedDevices: "الأجهزة المتخصصة",
        selectDevices: "اختر الأجهزة",
        washingMachine: "غسالة ملابس",
        heater: "سخان",
        oven: "فرن",
        refrigerator: "ثلاجة",
        airConditioner: "مكيف هواء",
        uploadNationalId: "تحميل الهوية الوطنية (وجه وقفا)",
        uploadCriminalRecord: "تحميل صحيفة الحالة الجنائية",
        liveSelfie: "التقاط صورة شخصية مباشرة",
        next: "التالي",
        submitAndSendForReview: "إرسال ومراجعة",
        applicationUnderReview: "طلبك قيد المراجعة. سيتم إعلامك بمجرد التحقق.",
        searchTechnicians: "ابحث عن فنيين",
        searchByDeviceType: "بحث حسب نوع الجهاز",
        searchByLocation: "بحث حسب الموقع",
        manageBookings: "إدارة الحجوزات",
        viewHistory: "عرض السجل",
        rateTechnician: "تقييم الفني",
        newServiceRequests: "طلبات خدمة جديدة",
        accept: "قبول",
        decline: "رفض",
        clientDetails: "تفاصيل العميل",
        updateJobStatus: "تحديث حالة العمل",
        inProgress: "قيد التنفيذ",
        completed: "مكتمل",
        rateClient: "تقييم العميل",
        english: "English",
        arabic: "العربية",
        splashLoading: "جاري التحميل...",
        welcomeTo: "مرحباً بك في",
        home: "الرئيسية",
        logout: "تسجيل الخروج",
        error: "خطأ",
        success: "نجاح",
        passwordRequired: "كلمة المرور مطلوبة",
        emailRequired: "البريد الإلكتروني مطلوب",
        nameRequired: "الاسم مطلوب",
        passwordsDontMatch: "كلمات المرور غير متطابقة",
        addressRequired: "العنوان مطلوب",
        phoneRequired: "رقم الهاتف مطلوب",
        devicesRequired: "يجب اختيار جهاز واحد على الأقل",
        loginSuccessful: "تم تسجيل الدخول بنجاح!",
        registrationSuccessful: "تم التسجيل بنجاح! رصيدك الأولي هو 0.",
        fieldRequired: "هذا الحقل مطلوب",
        allFieldsRequired: "جميع الحقول مطلوبة.",
        allDocumentsRequired: "جميع المستندات والصورة الشخصية مطلوبة.",
        applicationSubmitted: "تم تقديم الطلب بنجاح! سيتم توجيهك لتقييم المهارات.",
        noDevicesForAssessment: "لم يتم العثور على أجهزة متخصصة للتقييم. يرجى التسجيل مرة أخرى.",
        allQuestionsRequired: "يرجى الإجابة على جميع الأسئلة قبل الإرسال.",
        assessmentSubmitted: "تم إرسال تقييم المهارات بنجاح!",
        loadingAssessment: "جاري تحميل أسئلة التقييم أو لم يتم اختيار أجهزة...",
        typeYourAnswer: "اكتب إجابتك هنا...",
        assessmentFor: "تقييم لـ:",
        skillAssessment: "تقييم المهارات",
        skillAssessmentSubtitle: "يرجى الإجابة على الأسئلة التالية بناءً على تخصصاتك المختارة.",
        submittingAssessment: "جاري إرسال التقييم...",
        applicationPending: "الطلب قيد المراجعة",
        notificationViaPush: "سنقوم بإعلامك عبر الإشعارات الفورية والبريد الإلكتروني.",
        customerUserTypeDescription: "الوصول إلى الخدمات وحجز الفنيين.",
        technicianUserTypeDescription: "قدم مهاراتك وابحث عن وظائف.",
        loginSubtitle: "الرجاء إدخال بيانات الاعتماد الخاصة بك للوصول إلى حساب #{userType} الخاص بك.",
        loading: "جاري التحميل...",
        customerRegistrationSubtitle: "قم بإنشاء حساب عميل لبدء حجز الخدمات.",
        alreadyHaveAccount: "هل لديك حساب بالفعل؟ تسجيل الدخول",
        technicianRegistrationSubtitle: "انضم إلى شبكتنا من الفنيين المهرة.",
        step: "خطوة",
        uploadFront: "تحميل الوجه الأمامي",
        uploadBack: "تحميل الوجه الخلفي",
        noFileChosen: "لم يتم اختيار ملف",
        uploadDocument: "تحميل مستند",
        captureSelfie: "التقاط صورة شخصية",
        previous: "السابق",
        submitting: "جاري الإرسال...",
        multiSelectHint: "لأجهزة متعددة، حدد واحدًا. يمكن إضافة المزيد لاحقًا أو استخدام قائمة مفصولة بفواصل إذا سمح الإدخال بذلك.",
        manageBookingsDesc: "عرض وإدارة حجوزات الخدمة القادمة والنشطة.",
        viewBookings: "عرض الحجوزات",
        viewHistoryDesc: "تحقق من طلبات الخدمة السابقة وتفاعلات الفنيين.",
        viewServiceHistory: "عرض سجل الخدمة",
        rateTechnicianDesc: "تقديم ملاحظات حول الخدمات المكتملة لمساعدة الآخرين.",
        ratePreviousTechnicians: "تقييم الفنيين السابقين",
        availableTechnicians: "الفنيون المتاحون (الذين قبلوا طلبك وضمن 20 كم)",
        skills: "المهارات",
        bookNow: "احجز الآن",
        noTechniciansAvailable: "لا يوجد فنيون متاحون حاليًا في منطقتك أو يطابقون بحثك أو قبلوا طلبك.",
        newRequestsDesc: "عرض وإدارة طلبات الخدمة الواردة من العملاء.",
        viewRequests: "عرض الطلبات",
        rateClientDesc: "تقديم ملاحظات حول العملاء بعد إكمال المهمة.",
        ratePreviousClients: "تقييم العملاء السابقين",
        currentJobs: "الوظائف والطلبات الحالية",
        repair: "تصليح",
        maintenance: "صيانة",
        installation: "تركيب",
        new: "جديد",
        noCurrentJobs: "لا توجد وظائف حالية أو طلبات جديدة في الوقت الحالي.",
        createMaintenanceRequest: "إنشاء طلب صيانة",
        deviceType: "نوع الجهاز",
        issueDescription: "وصف المشكلة",
        visitFeeInfo: "يرجى العلم أن هناك رسوم زيارة للفني قدرها 100 جنيه مصري.",
        confirmRequest: "تأكيد الطلب ودفع الرسوم",
        insufficientBalance: "رصيد غير كاف لإنشاء الطلب. يرجى شحن حسابك.",
        requestCreatedSuccessfully: "تم إنشاء طلب الصيانة بنجاح. سيتم إخطار الفنيين المؤهلين.",
        checkingBalance: "جاري التحقق من الرصيد...",
        creatingRequest: "جاري إنشاء الطلب...",
        selectDeviceType: "اختر نوع الجهاز",
        describeTheIssue: "صف المشكلة بالتفصيل...",
        customerBalance: "رصيد العميل",
        currentBalance: "الرصيد الحالي: %{balance} جنيه مصري",
        addFunds: "إضافة رصيد",
        fundsAdded: "تمت إضافة %{amount} جنيه مصري إلى رصيدك.",
        acceptedTechnicians: "الفنيون الذين قبلوا طلبك",
        noAcceptedTechnicians: "لم يقبل أي فني طلبك بعد أو لا يوجد فنيون مطابقون في النطاق.",
        distance: "المسافة",
        contactTechnician: "اتصل بالفني",
        addBalanceTitle: "إضافة رصيد إلى حسابك",
        paymentMethod: "طريقة الدفع",
        instapay: "إنستا باي",
        vodafoneCash: "فودافون كاش",
        etisalatCash: "اتصالات كاش",
        amount: "المبلغ",
        amountPlaceholder: "أدخل المبلغ (الحد الأدنى 100 جنيه)",
        minAmountError: "الحد الأدنى للمبلغ هو 100 جنيه مصري.",
        proceedToPayment: "متابعة للدفع",
        paymentInstructionsTitle: "تعليمات الدفع",
        transferTo: "يرجى تحويل %{amount} جنيه مصري إلى:",
        instapayDetails: "حساب إنستا باي: m.shamroukh25@insapay",
        vodafoneCashDetails: "محفظة فودافون كاش: 01060070299",
        etisalatCashDetails: "محفظة اتصالات كاش: 01141003640",
        awaitingConfirmation: "في انتظار تأكيد التحويل من الإدارة. سيتم تحديث رصيدك بمجرد الموافقة.",
        transferConfirmed: "لقد قمت بالتحويل",
        paymentPending: "الدفع معلق. سيتم إعلامك عند تأكيد الإيداع.",
        paymentSuccessful: "تمت إضافة الرصيد بنجاح!",
        addBalanceDialogDescription: "اختر طريقة الدفع وأدخل المبلغ الذي ترغب في إضافته.",
        cancel: "إلغاء",
        close: "إغلاق",
        copiedToClipboard: "تم النسخ إلى الحافظة!",
        failedToCopy: "فشل النسخ.",
        transferSource: "مصدر التحويل (رقم الهاتف/عنوان المحفظة)",
        transferSourcePlaceholder: "أدخل رقم الهاتف أو عنوان المحفظة",
        uploadScreenshot: "تحميل لقطة شاشة التحويل",
        screenshotUploaded: "تم تحميل لقطة الشاشة بنجاح.",
        selectFile: "اختر ملف",
        transferSourceRequired: "مصدر التحويل مطلوب.",
        screenshotRequired: "لقطة شاشة التحويل مطلوبة.",
        wmq1: "صف خبرتك في إصلاح غسالات التحميل الأمامي.",
        wmq2: "ما هو السبب الشائع لعدم تصريف الغسالة للمياه؟",
        wmq2o1: "فلتر مسدود",
        wmq2o2: "مضخة معيبة",
        wmq2o3: "مفتاح غطاء مكسور",
        wmq2o4: "كل ما سبق",
        hq1: "اشرح عملية استكشاف أخطاء سخان المياه الذي لا ينتج ماء ساخن وإصلاحها.",
        oq1: "إذا كان الفرن الكهربائي لا يسخن، ما هو أول مكون ستفحصه؟",
        oq1o1: "عنصر التسخين",
        oq1o2: "الثرموستات",
        oq1o3: "مفتاح الاختيار",
        rq1: "ما هي الخطوات التي ستتخذها لتشخيص الثلاجة التي لا تبرد بشكل صحيح؟",
        acq1: "صف كيف يمكنك التحقق من تسربات غاز التبريد في وحدة التكييف."
      },
      en: {
        appName: "Fast Fix",
        tagline: "Quick and Efficient Home Appliance Maintenance",
        customer: "Customer",
        technician: "Technician",
        selectUserType: "Select User Type",
        login: "Login",
        email: "Email",
        password: "Password",
        forgotPassword: "Forgot password?",
        createNewAccount: "Create new account",
        register: "Register",
        fullName: "Full Name",
        confirmPassword: "Confirm Password",
        fullAddress: "Full Address",
        mobileNumber: "Mobile Number",
        specializedDevices: "Specialized Devices",
        selectDevices: "Select Devices",
        washingMachine: "Washing Machine",
        heater: "Heater",
        oven: "Oven",
        refrigerator: "Refrigerator",
        airConditioner: "Air Conditioner",
        uploadNationalId: "Upload National ID (Front & Back)",
        uploadCriminalRecord: "Upload Criminal Record Document",
        liveSelfie: "Live Selfie Capture",
        next: "Next",
        submitAndSendForReview: "Submit and Send for Review",
        applicationUnderReview: "Your application is under review. You will be notified once verified.",
        searchTechnicians: "Search for Technicians",
        searchByDeviceType: "Search by Device Type",
        searchByLocation: "Search by Location",
        manageBookings: "Manage Bookings",
        viewHistory: "View History",
        rateTechnician: "Rate Technician",
        newServiceRequests: "New Service Requests",
        accept: "Accept",
        decline: "Decline",
        clientDetails: "Client Details",
        updateJobStatus: "Update Job Status",
        inProgress: "In Progress",
        completed: "Completed",
        rateClient: "Rate Client",
        english: "English",
        arabic: "العربية",
        splashLoading: "Loading...",
        welcomeTo: "Welcome to",
        home: "Home",
        logout: "Logout",
        error: "Error",
        success: "Success",
        passwordRequired: "Password is required",
        emailRequired: "Email is required",
        nameRequired: "Name is required",
        passwordsDontMatch: "Passwords do not match",
        addressRequired: "Address is required",
        phoneRequired: "Phone number is required",
        devicesRequired: "At least one device must be selected",
        loginSuccessful: "Login successful!",
        registrationSuccessful: "Registration successful! Your initial balance is 0.",
        fieldRequired: "This field is required",
        allFieldsRequired: "All fields are required.",
        allDocumentsRequired: "All documents and selfie are required.",
        applicationSubmitted: "Application submitted successfully! You will be redirected for skill assessment.",
        noDevicesForAssessment: "No specialized devices found for assessment. Please register again.",
        allQuestionsRequired: "Please answer all questions before submitting.",
        assessmentSubmitted: "Skill assessment submitted successfully!",
        loadingAssessment: "Loading assessment questions or no devices selected...",
        typeYourAnswer: "Type your answer here...",
        assessmentFor: "Assessment for:",
        skillAssessment: "Skill Assessment",
        skillAssessmentSubtitle: "Please answer the following questions based on your selected specializations.",
        submittingAssessment: "Submitting Assessment...",
        applicationPending: "Application Pending Review",
        notificationViaPush: "We will notify you via push notification and email.",
        customerUserTypeDescription: "Access services and book technicians.",
        technicianUserTypeDescription: "Offer your skills and find jobs.",
        loginSubtitle: "Please enter your credentials to access your #{userType} account.",
        loading: "Loading...",
        customerRegistrationSubtitle: "Create your customer account to start booking services.",
        alreadyHaveAccount: "Already have an account? Login",
        technicianRegistrationSubtitle: "Join our network of skilled technicians.",
        step: "Step",
        uploadFront: "Upload Front",
        uploadBack: "Upload Back",
        noFileChosen: "No file chosen",
        uploadDocument: "Upload Document",
        captureSelfie: "Capture Selfie",
        previous: "Previous",
        submitting: "Submitting...",
        multiSelectHint: "For multiple devices, select one. More can be added later or use a comma-separated list if input allows.",
        manageBookingsDesc: "View and manage your upcoming and active service bookings.",
        viewBookings: "View Bookings",
        viewHistoryDesc: "Check your past service requests and technician interactions.",
        viewServiceHistory: "View Service History",
        rateTechnicianDesc: "Provide feedback on completed services to help others.",
        ratePreviousTechnicians: "Rate Technicians",
        availableTechnicians: "Available Technicians (Accepted your request & within 20km)",
        skills: "Skills",
        bookNow: "Book Now",
        noTechniciansAvailable: "No technicians currently available in your area, matching your search, or have accepted your request.",
        newRequestsDesc: "View and manage incoming service requests from customers.",
        viewRequests: "View Requests",
        rateClientDesc: "Provide feedback on clients after completing a job.",
        ratePreviousClients: "Rate Clients",
        currentJobs: "Current Jobs & Requests",
        repair: "Repair",
        maintenance: "Maintenance",
        installation: "Installation",
        new: "New",
        noCurrentJobs: "No current jobs or new requests at the moment.",
        createMaintenanceRequest: "Create Maintenance Request",
        deviceType: "Device Type",
        issueDescription: "Issue Description",
        visitFeeInfo: "Please note: There is a technician visit fee of 100 EGP.",
        confirmRequest: "Confirm Request & Pay Fee",
        insufficientBalance: "Insufficient balance to create the request. Please add funds to your account.",
        requestCreatedSuccessfully: "Maintenance request created successfully. Qualified technicians will be notified.",
        checkingBalance: "Checking balance...",
        creatingRequest: "Creating request...",
        selectDeviceType: "Select Device Type",
        describeTheIssue: "Describe the issue in detail...",
        customerBalance: "Customer Balance",
        currentBalance: "Current Balance: %{balance} EGP",
        addFunds: "Add Funds",
        fundsAdded: "%{amount} EGP added to your balance.",
        acceptedTechnicians: "Technicians Who Accepted Your Request",
        noAcceptedTechnicians: "No technicians have accepted your request yet or none match the criteria.",
        distance: "Distance",
        contactTechnician: "Contact Technician",
        addBalanceTitle: "Add Balance to Your Account",
        paymentMethod: "Payment Method",
        instapay: "InstaPay",
        vodafoneCash: "Vodafone Cash",
        etisalatCash: "Etisalat Cash",
        amount: "Amount",
        amountPlaceholder: "Enter amount (min 100 EGP)",
        minAmountError: "Minimum amount is 100 EGP.",
        proceedToPayment: "Proceed to Payment",
        paymentInstructionsTitle: "Payment Instructions",
        transferTo: "Please transfer %{amount} EGP to:",
        instapayDetails: "InstaPay Account: m.shamroukh25@insapay",
        vodafoneCashDetails: "Vodafone Cash Wallet: 01060070299",
        etisalatCashDetails: "Etisalat Cash Wallet: 01141003640",
        awaitingConfirmation: "Awaiting transfer confirmation from management. Your balance will be updated upon approval.",
        transferConfirmed: "I Have Made The Transfer",
        paymentPending: "Payment pending. You will be notified once the deposit is confirmed.",
        paymentSuccessful: "Balance added successfully!",
        addBalanceDialogDescription: "Select your payment method and enter the amount you wish to add.",
        cancel: "Cancel",
        close: "Close",
        copiedToClipboard: "Copied to clipboard!",
        failedToCopy: "Failed to copy.",
        transferSource: "Transfer Source (Phone/Wallet Address)",
        transferSourcePlaceholder: "Enter phone number or wallet address",
        uploadScreenshot: "Upload Transfer Screenshot",
        screenshotUploaded: "Screenshot uploaded successfully.",
        selectFile: "Select file",
        transferSourceRequired: "Transfer source is required.",
        screenshotRequired: "Transfer screenshot is required.",
        wmq1: "Describe your experience with repairing front-load washing machines.",
        wmq2: "What is a common cause of a washing machine not draining?",
        wmq2o1: "Clogged filter",
        wmq2o2: "Faulty pump",
        wmq2o3: "Broken lid switch",
        wmq2o4: "All of the above",
        hq1: "Explain the process of troubleshooting a water heater that's not producing hot water.",
        oq1: "If an electric oven isn't heating, what's the first component you would check?",
        oq1o1: "Heating element",
        oq1o2: "Thermostat",
        oq1o3: "Selector switch",
        rq1: "What steps would you take to diagnose a refrigerator that is not cooling properly?",
        acq1: "Describe how you would check for refrigerant leaks in an AC unit."
      },
    };

    export const LanguageProvider = ({ children }) => {
      const [language, setLanguage] = useState('ar'); 

      useEffect(() => {
        document.documentElement.lang = language;
        document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
      }, [language]);

      const toggleLanguage = () => {
        setLanguage((prevLang) => (prevLang === 'ar' ? 'en' : 'ar'));
      };

      const t = (key, params = {}) => {
        let translation = translations[language][key] || key;
        if (typeof translation === 'string') {
            Object.keys(params).forEach(paramKey => {
                translation = translation.replace(`%{${paramKey}}`, params[paramKey]);
            });
        }
        return translation;
      };

      return (
        <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
          {children}
        </LanguageContext.Provider>
      );
    };

    export const useLanguage = () => useContext(LanguageContext);
  